/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.vehicle.feedback;

import javax.swing.ImageIcon;

/**
 *
 * @author shahi
 */
public class FeedbackItem extends javax.swing.JPanel {

    public FeedbackItem(String title, byte[] img, String comment) {
        initComponents();
        header.setText(title);
        
        if (img != null) {
            ImageIcon img1 = new ImageIcon(img);
            image.setImage(img1);
        }
        
        cmt.setText(comment);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new app.vehicle.design.ImageAvatar();
        header = new javax.swing.JLabel();
        cmt = new javax.swing.JLabel();

        image.setBorderSize(4);
        image.setBorderSpace(3);
        image.setGradientColor1(new java.awt.Color(255, 102, 0));
        image.setGradientColor2(new java.awt.Color(255, 255, 0));

        header.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        header.setText("Saugat Shahi Thakuri");

        cmt.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cmt.setText("Everything is nice and working!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header)
                    .addComponent(cmt))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmt)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cmt;
    private javax.swing.JLabel header;
    private app.vehicle.design.ImageAvatar image;
    // End of variables declaration//GEN-END:variables
}
