package app.vehicle.form;

import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

public class CouponCodes extends javax.swing.JPanel {
    
    private final String couponCode;
    private String description;

    public CouponCodes(String code, String desc) {
        
        initComponents();
        
        this.couponCode = code;
        this.description = desc;
        
        codeNumber.setText(code);
        jLabel1.setText(desc);
        
        copyCode.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    private void copyToClipboard(String couponCode) {
        StringSelection stringSelection = new StringSelection(couponCode);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
    }

    public String getCouponCode() {
        return couponCode;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rewardBox = new javax.swing.JLabel();
        codeNumber = new javax.swing.JLabel();
        copyCode = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 240, 240));

        rewardBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/dashboard/png/Layer 2 (1).png"))); // NOI18N

        codeNumber.setText("CARVCX20");

        copyCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/dashboard/png/Group 34.png"))); // NOI18N
        copyCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                copyCodeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rewardBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codeNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(copyCode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rewardBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(copyCode)
                            .addComponent(codeNumber))
                        .addGap(9, 9, 9)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void copyCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyCodeMouseClicked
        String cpCode = getCouponCode();
        copyToClipboard(cpCode);
        
        copyCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/dashboard/png/Group 35 (1).png")));
        Timer timer = new Timer(1000, (ActionEvent e) -> {
            copyCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/dashboard/png/Group 34.png")));
            copyCode.setText("");
        });
        
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_copyCodeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codeNumber;
    private javax.swing.JLabel copyCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel rewardBox;
    // End of variables declaration//GEN-END:variables
}
