package app.vehicle.form;

import app.vehicle.design.DataSearch;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author shahi
 */
public class SearchItems extends javax.swing.JPanel {

    public SearchItems(DataSearch data) {
        initComponents();
        setData(data);
    }
    
    private void setData(DataSearch data) {
        addEventMouse(this);
        addEventMouse(labelText);
        addEventMouse(labelRemove);
        
        labelText.setText(data.getText());
        labelText.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        
        if(data.isVehicles()) {
            labelText.setForeground(Color.decode("#FF5C00"));
            labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/dashboard/png/Vector (2).png")));
            labelRemove.setCursor(new Cursor(Cursor.HAND_CURSOR));
        } else {
            labelRemove.setText("");
        }
    }
    
    private void addEventMouse(Component com) {
        com.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                setBackground(Color.decode("#F0F0F0"));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                setBackground(Color.white);
            }
        });
    }
    
    private ActionListener eventClick;
    private ActionListener eventRemove;
    
    public void addEvent(ActionListener eventClick, ActionListener eventRemove) {
        this.eventClick = eventClick;
        this.eventRemove = eventRemove;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        labelIcon = new javax.swing.JLabel();
        labelText = new javax.swing.JLabel();
        labelRemove = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setBackground(new java.awt.Color(255, 255, 255));

        labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/dashboard/png/Search (1).png"))); // NOI18N
        labelIcon.setIconTextGap(12);

        labelText.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        labelText.setText("Saugat Shahi Thakuri");
        labelText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTextMouseClicked(evt);
            }
        });

        labelRemove.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        labelRemove.setText("Remove");
        labelRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRemoveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelText, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelText, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(labelRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRemoveMouseClicked
        if (!labelRemove.getText().trim().equals("")) {
            eventRemove.actionPerformed(null);
        }
    }//GEN-LAST:event_labelRemoveMouseClicked

    private void labelTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTextMouseClicked
        eventClick.actionPerformed(null);
    }//GEN-LAST:event_labelTextMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel labelRemove;
    private javax.swing.JLabel labelText;
    // End of variables declaration//GEN-END:variables
}
